# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

image_Compression <- function(img, num) {
    .Call(`_SIP_image_Compression`, img, num)
}

image_Edging <- function(img) {
    .Call(`_SIP_image_Edging`, img)
}

image_Sharpening <- function(img) {
    .Call(`_SIP_image_Sharpening`, img)
}

randomEncryption <- function(img) {
    .Call(`_SIP_randomEncryption`, img)
}

randomDecryption <- function(img, key) {
    .Call(`_SIP_randomDecryption`, img, key)
}

simpleEncryption <- function(source, mask, percent = 0.5) {
    .Call(`_SIP_simpleEncryption`, source, mask, percent)
}

simpleDecryption <- function(img, mask, percent) {
    .Call(`_SIP_simpleDecryption`, img, mask, percent)
}

simpleEnhancement <- function(img, k = 0.5, b = 0.5) {
    .Call(`_SIP_simpleEnhancement`, img, k, b)
}

